version: '3.9'

networks:
  nias_server_network:


services:
  web:
    build: 
      context: ./server-web-page
      args:
        - WEB_PAGE_PORT=${WEB_PAGE_PORT}
    image: ${WEB_PAGE_NAME}:${WEB_PAGE_VERSION}
    environment:
      - QUEUE_NAME=${QUEUE_NAME}
      - BROKER_NAME=${BROKER_NAME}
    container_name: ${WEB_PAGE_NAME}
    
    ports:
      - "${WEB_PAGE_PORT}:${WEB_PAGE_PORT}"
    networks:
      - nias_server_network
    depends_on:
      - queue
  
  queue:
    build: 
      context: ./rabbitmq-queue
      args:
        - QUEUE_INTERFACE_PORT=${QUEUE_INTERFACE_PORT}
    image: ${BROKER_NAME}:${BROKER_VERSION}
    container_name: ${BROKER_NAME}
    ports:
      - "${QUEUE_INTERFACE_PORT}:${QUEUE_INTERFACE_PORT}"
      - "${QUEUE_CONFIG_PORT}:${QUEUE_CONFIG_PORT}"
    networks:
      - nias_server_network
   
  consumer:
    build: 
      context: ./consumer
      args:
        - QUEUE_CONSUMER_PORT=${QUEUE_CONSUMER_PORT}
    image: ${QUEUE_CONSUMER_NAME}:${QUEUE_CONSUMER_VERSION}
    environment:
      - PROCESS_UNITY_NAME=${PROCESS_UNITY_NAME}
      - PROCESS_UNITY_PORT=${PROCESS_UNITY_PORT}
      - QUEUE_NAME=${QUEUE_NAME}
      - BROKER_NAME=${BROKER_NAME}
    container_name: ${QUEUE_CONSUMER_NAME}
    ports:
     - "${QUEUE_CONSUMER_PORT}:${QUEUE_CONSUMER_PORT}"
    networks:
      - nias_server_network
    depends_on:
      queue:
        condition: service_healthy
        restart: true
      process-unity1:
        condition: service_started
    
  process-unity1:
    build: 
      context: ./process-unity
      args:
        - PROCESS_UNITY_PORT=${PROCESS_UNITY_PORT}
    image: process-unity:${PROCESS_UNITY_PYTHON_VERSION}
    environment:
      - PROCESS_UNITY_PORT=${PROCESS_UNITY_PORT}
    container_name: ${PROCESS_UNITY_NAME}
    ports:
      - "${PROCESS_UNITY_PORT}:${PROCESS_UNITY_PORT}"
    networks:
      - nias_server_network
    volumes:
      - nias_server_volume:/app/output

volumes:
  nias_server_volume:

