FROM python:3.8-slim-buster
 
RUN mkdir /code\
    && mkdir /input\
    && mkdir /output
 
COPY ./project/code /code
 
COPY ./project/input /input

RUN apt-get update\
    && pip install --upgrade pip\
    && pip install -r /code/requirements.txt

ENTRYPOINT [ "python3" , "/code/app.py" ]

