#! /bin/bash

###Obtaining informations to create a new job###
#Getting the username
echo "Digite o nome do usuário do usuário"
read user
while ! [ -e /home/$user ]
do
	echo "Usuário não existe, digite novamente ou digite 'out' para sair e solicite a criação de um novo usuário "
	read user

	if [ $user = out ]
	then
		exit
	fi
done

#Defining the name of the new project
echo "Digite o nome do projeto (Deve ser escrito em letras minusculas e sem espaço)"
read projeto
while [ -O $projeto ]
do
	echo "Este projeto já existe, por favor digitar novo nome"
	read projeto
done

#Asking for the path of the project in the user's PC
echo "Digite o caminho completo para a pasta de origem do projeto"
read path

#Defining the type of the project (Python or MATLAB)
echo "Digite python ou p para projetos em python, matlab ou m para projetos em matlab"
read tipo

while [ $tipo != python ] && [ $tipo != p ] && [ $tipo != matlab ] && [ $tipo != m ]
	
do
	echo "Tipo inválido, digite novamente (python ou p para projetos em python, matlab ou m para projetos em matlab)"
	read tipo
done

#Function to build the image and run a container for the project 
docker_build_run () {
	
	docker build -t $projeto:latest /home/$user/$projeto/
	docker run --rm --name "$projeto-container" -it \
		-v /home/$user/$projeto/project/output:/output \
		$projeto:latest
	}

#Creating a directory to store the files of the new project and filling it with a copy of the given path
mkdir /home/$user/$projeto
echo "Digite a senha de usuário do seu computador pessoal"
scp -r $user:$path /home/$user/$projeto

#Copying partinent Dockerfile from tamplates directory depending on the project type
case $tipo in
	python | p)
		cp /home/templates/dockerfile-python /home/$user/$projeto/Dockerfile
		;;

	matlab | m)
		cp /home/templates/dockerfile-matlab /home/$user/$projeto/Dockerfile
		;;

	esac

#Running the docker function 
docker_build_run


